const MISTRAL_API_KEY = "HERE_API_KEY"
const NOTION_API_KEY = "HERE_API_KEY"
const NOTION_DATABASE_ID = "HERE_API_KEY"
const HUGGING_FACE_API_KEY = "HERE_API_KEY"


export { MISTRAL_API_KEY, NOTION_API_KEY, NOTION_DATABASE_ID, HUGGING_FACE_API_KEY }

